### ISSUE TITLE
How to add the real name to the requester's email?

### ISSUE THREAD

**Issue by tivnet** [Helprace/Helprace-REST-API-examples#1]
Hi, in the API sample below, what would be a proper syntax for the email with the user's name?
I have tried `John Doe <me@example.com>` and got
```
  [0] => stdClass Object
                (
                    [field] => requester
                    [type] => emailAddressInvalid
                    [message] => John Doe <me@example.com> - Doesn't look like a valid email.
                )
```
Thank you!

### The API example

```php
// Create a new ticket with a minimum set of required fields
$ticket_data = json_encode(array(
  "body" => "Content of a sample ticket <br>created via API",
  "subject" => "Sample ticket created via API",
  "requester" => "email@example.com" // <------- Name here?
));
```

**Comment by Thealoner** [comment]
It is not possible to add user's name in the Create Ticket request, unfortunately. It works in accordance to the ticket submission in the UI: user only specifies their email there, but not his name.
If you need to specify user name, use [Create User](https://helprace.com/developers/api/#!/Users/put_api_v1_users) before creating ticket or [Update User](https://helprace.com/developers/api/#!/Users/post_api_v1_users_user_id) after ticket is created.

**Comment by tivnet** [comment]
@Thealoner 
Thanks, `Update User` works fine. Having an optional Name in `Create Ticket` would save the extra API call and would make the whole procedure more reliable, though.

**Comment by Thealoner** [comment]
@tivnet Thanks for suggestion!
